"""
I/O converters for interoperability with other nuclear codes.

Provides import/export functionality for Serpent and OpenMC formats.
Community edition uses placeholders; SMRForge Pro provides full implementation.
"""

from pathlib import Path
from typing import Dict, List, Optional, Any
import json
import numpy as np

from ..utils.logging import get_logger

logger = get_logger("smrforge.io.converters")

# Pro delegation: use smrforge_pro if available
try:
    from smrforge_pro.converters.serpent import SerpentConverter as _ProSerpentConverter  # pragma: no cover
    from smrforge_pro.converters.openmc import OpenMCConverter as _ProOpenMCConverter  # pragma: no cover
    _PRO_AVAILABLE = True  # pragma: no cover
except ImportError:  # pragma: no cover
    _ProSerpentConverter = None  # type: ignore
    _ProOpenMCConverter = None  # type: ignore
    _PRO_AVAILABLE = False

_UPGRADE_MSG = (
    "Full Serpent/OpenMC converters require SMRForge Pro. "
    "Upgrade at https://smrforge.io or install smrforge-pro."
)


class SerpentConverter:
    """
    Converter for Serpent format.

    Community: placeholder. Pro: full export/import. Delegate to smrforge_pro if available.
    """

    @staticmethod
    def export_reactor(reactor, output_file: Path):
        """
        Export reactor to Serpent format.

        Args:
            reactor: Reactor instance
            output_file: Output file path

        Raises:
            OSError: If the output file cannot be written.
        """
        if _PRO_AVAILABLE and _ProSerpentConverter is not None:  # pragma: no cover
            _ProSerpentConverter.export_reactor(reactor, Path(output_file))
            return
        logger.warning(_UPGRADE_MSG)
        logger.warning("Serpent export is a placeholder - full implementation requires Pro")
        with open(output_file, 'w') as f:
            f.write("% Serpent input file generated by SMRForge (Community)\n")
            f.write("% Upgrade to Pro for full export: https://smrforge.io\n")
            f.write("\n")
            f.write("% Geometry definition would go here\n")
            f.write("% Material definitions would go here\n")

    @staticmethod
    def import_reactor(input_file: Path) -> Dict[str, Any]:
        """
        Import reactor from Serpent format.

        Args:
            input_file: Input file path

        Returns:
            Dictionary with 'core', 'source', 'format'; or for Pro full PrismaticCore import.
        """
        if _PRO_AVAILABLE and _ProSerpentConverter is not None:  # pragma: no cover
            return _ProSerpentConverter.import_reactor(Path(input_file))
        logger.warning(_UPGRADE_MSG)
        raise NotImplementedError(
            "Serpent import requires SMRForge Pro. Upgrade at https://smrforge.io"
        )


class OpenMCConverter:
    """
    Converter for OpenMC format.

    Community: placeholder. Pro: full export/import. Delegate to smrforge_pro if available.
    """

    @staticmethod
    def export_reactor(reactor, output_dir: Path):
        """
        Export reactor to OpenMC format.

        Args:
            reactor: Reactor instance
            output_dir: Output directory for geometry.xml and materials.xml

        Raises:
            OSError: If the output directory or files cannot be created.
        """
        if _PRO_AVAILABLE and _ProOpenMCConverter is not None:  # pragma: no cover
            _ProOpenMCConverter.export_reactor(reactor, Path(output_dir))
            return
        logger.warning(_UPGRADE_MSG)
        logger.warning("OpenMC export is a placeholder - full implementation requires Pro")
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        geometry_file = output_dir / "geometry.xml"
        with open(geometry_file, 'w') as f:
            f.write('<?xml version="1.0"?>\n')
            f.write('<geometry>\n')
            f.write('  <!-- OpenMC geometry generated by SMRForge (Community) -->\n')
            f.write('  <!-- Upgrade to Pro for full export: https://smrforge.io -->\n')
            f.write('</geometry>\n')
        materials_file = output_dir / "materials.xml"
        with open(materials_file, 'w') as f:
            f.write('<?xml version="1.0"?>\n')
            f.write('<materials>\n')
            f.write('  <!-- OpenMC materials generated by SMRForge (Community) -->\n')
            f.write('  <!-- Upgrade to Pro: https://smrforge.io -->\n')
            f.write('</materials>\n')

    @staticmethod
    def import_reactor(geometry_file: Path, materials_file: Optional[Path] = None) -> Dict[str, Any]:
        """
        Import reactor from OpenMC format.

        Args:
            geometry_file: Path to geometry.xml
            materials_file: Optional path to materials.xml

        Returns:
            Dictionary with 'core', 'source', 'format'; or for Pro full PrismaticCore import.
        """
        if _PRO_AVAILABLE and _ProOpenMCConverter is not None:  # pragma: no cover
            return _ProOpenMCConverter.import_reactor(
                Path(geometry_file),
                Path(materials_file) if materials_file else None,
            )
        logger.warning(_UPGRADE_MSG)
        raise NotImplementedError(
            "OpenMC import requires SMRForge Pro. Upgrade at https://smrforge.io"
        )
