"""
I/O converters for interoperability with other nuclear codes.

Provides import/export functionality for Serpent, OpenMC, and MCNP formats.
Community edition uses placeholders for Serpent/MCNP; SMRForge Pro provides full implementation.
OpenMC has full Community export/import.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import numpy as np

from ..utils.logging import get_logger
from ..workflows.plugin_registry import run_hooks

logger = get_logger("smrforge.io.converters")

# Pro delegation: use smrforge_pro if available
try:
    from smrforge_pro.converters.openmc import (
        OpenMCConverter as _ProOpenMCConverter,  # pragma: no cover
    )
    from smrforge_pro.converters.serpent import (
        SerpentConverter as _ProSerpentConverter,  # pragma: no cover
    )
    from smrforge_pro.converters.mcnp import (
        MCNPConverter as _ProMCNPConverter,  # pragma: no cover
    )

    _PRO_AVAILABLE = True  # pragma: no cover
except ImportError:  # pragma: no cover
    _ProSerpentConverter = None  # type: ignore
    _ProOpenMCConverter = None  # type: ignore
    _ProMCNPConverter = None  # type: ignore
    _PRO_AVAILABLE = False

_UPGRADE_MSG = (
    "Full Serpent/OpenMC converters require SMRForge Pro. "
    "Upgrade at https://smrforge.io or install smrforge-pro."
)


class SerpentConverter:
    """
    Converter for Serpent format.

    Community: placeholder export/import; serpent_run provides run + parse_res for round-trip.
    Pro: full export/import. Delegate to smrforge_pro if available.

    Round-trip workflow: Pro export_reactor -> run_serpent -> parse_res_file -> use in SMRForge.
    """

    @staticmethod
    def export_reactor(reactor: Any, output_file: Union[str, Path]) -> None:
        """
        Export reactor to Serpent format.

        Args:
            reactor: Reactor instance
            output_file: Output file path

        Raises:
            OSError: If the output file cannot be written.
        """
        run_hooks("pre_export", context={"format": "serpent", "reactor": reactor, "output_file": output_file})
        if _PRO_AVAILABLE and _ProSerpentConverter is not None:  # pragma: no cover
            _ProSerpentConverter.export_reactor(reactor, Path(output_file))
            return
        logger.warning(_UPGRADE_MSG)
        logger.warning(
            "Serpent export is a placeholder - full implementation requires Pro"
        )
        with open(output_file, "w") as f:
            f.write("% Serpent input file generated by SMRForge (Community)\n")
            f.write("% Upgrade to Pro for full export: https://smrforge.io\n")
            f.write("\n")
            f.write("% Geometry definition would go here\n")
            f.write("% Material definitions would go here\n")

    @staticmethod
    def import_reactor(input_file: Union[str, Path]) -> Dict[str, Any]:
        """
        Import reactor from Serpent format.

        Args:
            input_file: Input file path

        Returns:
            Dictionary with 'core', 'source', 'format'; or for Pro full PrismaticCore import.
        """
        if _PRO_AVAILABLE and _ProSerpentConverter is not None:  # pragma: no cover
            return _ProSerpentConverter.import_reactor(Path(input_file))
        logger.warning(_UPGRADE_MSG)
        raise NotImplementedError(
            "Serpent import requires SMRForge Pro. Upgrade at https://smrforge.io"
        )


class OpenMCConverter:
    """
    Converter for OpenMC format.

    Community: full export/import; Pro: enhanced implementation if available.
    """

    @staticmethod
    def export_reactor(
        reactor: Any,
        output_dir: Union[str, Path],
        particles: int = 1000,
        batches: int = 20,
    ) -> None:
        """
        Export reactor to OpenMC format.

        Args:
            reactor: Reactor instance (SimpleReactor, preset, or PrismaticCore/PebbleBedCore)
            output_dir: Output directory for geometry.xml, materials.xml, settings.xml
            particles: Neutrons per generation (default 1000)
            batches: Number of batches (default 20)

        Raises:
            ValueError: If reactor has no core geometry
            OSError: If the output directory or files cannot be created.
        """
        if _PRO_AVAILABLE and _ProOpenMCConverter is not None:  # pragma: no cover
            _ProOpenMCConverter.export_reactor(reactor, Path(output_dir))
            return
        from smrforge.io.openmc_export import export_reactor_to_openmc

        export_reactor_to_openmc(
            reactor,
            Path(output_dir),
            particles=particles,
            batches=batches,
        )

    @staticmethod
    def import_reactor(
        geometry_file: Union[str, Path],
        materials_file: Optional[Union[str, Path]] = None,
    ) -> Dict[str, Any]:
        """
        Import reactor from OpenMC format.

        Args:
            geometry_file: Path to geometry.xml
            materials_file: Optional path to materials.xml

        Returns:
            Dictionary with 'core', 'source', 'format'; or for Pro full PrismaticCore import.
        """
        if _PRO_AVAILABLE and _ProOpenMCConverter is not None:  # pragma: no cover
            return _ProOpenMCConverter.import_reactor(
                Path(geometry_file),
                Path(materials_file) if materials_file else None,
            )
        from smrforge.io.openmc_import import import_reactor_from_openmc

        return import_reactor_from_openmc(
            Path(geometry_file),
            Path(materials_file) if materials_file else None,
        )


class MCNPConverter:
    """
    Converter for MCNP format.

    Community: placeholder export; Pro: full implementation. Delegate to Pro when available.
    """

    @staticmethod
    def export_reactor(reactor: Any, output_file: Union[str, Path]) -> None:
        """
        Export reactor to MCNP format.

        Args:
            reactor: Reactor instance (PrismaticCore, PebbleBedCore, etc.)
            output_file: Output file path (.mcnp or .inp)

        Raises:
            OSError: If the output file cannot be written.
        """
        run_hooks("pre_export", context={"format": "mcnp", "reactor": reactor, "output_file": output_file})
        if _PRO_AVAILABLE and _ProMCNPConverter is not None:  # pragma: no cover
            _ProMCNPConverter.export_reactor(reactor, Path(output_file))
            return
        output_file = Path(output_file)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, "w") as f:
            f.write("C MCNP input file generated by SMRForge (Community)\n")
            f.write("C Full MCNP export available in SMRForge Pro: https://smrforge.io\n")
            f.write("C\n")
            f.write("C Cell cards would go here\n")
            f.write("C Surface cards would go here\n")
            f.write("C Material cards would go here\n")
        logger.info(f"MCNP placeholder written to {output_file} (full export requires Pro)")
