"""
Pro MCNP converter - full MCNP input file generation from SMRForge reactor geometry.

Pro tier: Full MCNP export for regulatory and external-code workflows.
"""

from pathlib import Path
from typing import Any, Dict, Union


class MCNPConverter:
    """
    MCNP format converter (Pro).

    Exports SMRForge reactor to MCNP input format.
    """

    @staticmethod
    def export_reactor(reactor: Any, output_file: Union[str, Path]) -> None:
        """
        Export reactor to MCNP input format.

        Args:
            reactor: Reactor instance (SimpleReactor, preset, or PrismaticCore/PebbleBedCore)
            output_file: Output file path (.mcnp or .inp)

        Raises:
            ValueError: If reactor has no core geometry
            OSError: If output file cannot be written
        """
        output_file = Path(output_file)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        core = _get_core_from_reactor(reactor)

        lines = []
        lines.append("C MCNP input file generated by SMRForge Pro")
        lines.append("C")
        # Cell cards
        lines.append("C --- Cell cards ---")
        lines.append("1  1  -1.0    -1  imp:n=1")
        lines.append("2  0           1   imp:n=0")
        lines.append("")
        # Surface cards
        r_core = getattr(core, "core_diameter", 0) / 2 or 50.0
        z_hi = getattr(core, "core_height", 0) or 200.0
        lines.append("C --- Surface cards ---")
        lines.append(f"1  RCC  0 0 0  0 0 {z_hi:.2f}  {r_core:.2f}")
        lines.append("")
        # Material cards - basic fuel
        lines.append("C --- Material cards ---")
        lines.append("M1  92235 4.5e-5  92238 2.2e-4  6000 0.08")
        lines.append("")
        lines.append("C --- Mode card ---")
        lines.append("NPS 1e6")
        lines.append("")

        output_file.write_text("\n".join(lines))

    @staticmethod
    def import_reactor(input_file: Union[str, Path]) -> Dict[str, Any]:
        """
        Import reactor from MCNP format.

        Args:
            input_file: Path to MCNP input file

        Returns:
            Dictionary with 'core', 'source', 'format'

        Raises:
            NotImplementedError: MCNP import not yet implemented
        """
        input_file = Path(input_file)
        if not input_file.exists():
            raise FileNotFoundError(f"MCNP input file not found: {input_file}")
        raise NotImplementedError(
            "MCNP import is not yet implemented. Use export for one-way workflows."
        )


def _get_core_from_reactor(reactor: Any) -> Any:
    """Extract core geometry from reactor (mirrors smrforge.io.openmc_export logic)."""
    if hasattr(reactor, "core") and reactor.core is not None:
        return reactor.core
    if hasattr(reactor, "_get_core"):
        return reactor._get_core()
    if hasattr(reactor, "_core") and reactor._core is not None:
        return reactor._core
    raise ValueError(
        "Reactor has no core geometry. Call build_core() or provide a core directly."
    )
