"""
Pro Serpent converter - full export/import for Serpent format.

Pro tier: Full Serpent input file generation from SMRForge reactor geometry.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional, Union


class SerpentConverter:
    """
    Serpent format converter (Pro).

    Exports SMRForge reactor to Serpent input; import requires parsing (NotImplemented).
    """

    @staticmethod
    def export_reactor(reactor: Any, output_file: Union[str, Path]) -> None:
        """
        Export reactor to Serpent input format.

        Args:
            reactor: Reactor instance (SimpleReactor, preset, or PrismaticCore/PebbleBedCore)
            output_file: Output file path (.serp or .input)

        Raises:
            ValueError: If reactor has no core geometry
            OSError: If output file cannot be written
        """
        output_file = Path(output_file)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        core = _get_core_from_reactor(reactor)

        lines: List[str] = []
        lines.append("% Serpent input file generated by SMRForge Pro")
        lines.append("%")

        # Title
        title = getattr(reactor, "name", None) or getattr(core, "core_type", "SMRForge")
        lines.append(f"set title {repr(str(title))}")
        lines.append("")

        # Materials section - basic fuel and graphite
        lines.append("% --- Materials ---")
        lines.append("mat fuel  moder graph 600   burn 1")
        lines.append("  92235.09c  -4.5e-5")
        lines.append("  92238.09c  -2.2e-4")
        lines.append("  6000.09c   -0.08")
        lines.append("")
        lines.append("mat graph  moder graph 600")
        lines.append("  6000.09c   -0.08")
        lines.append("")

        # Surfaces
        r_core = (
            getattr(core, "core_diameter", 0) / 2
            or 50.0
        )
        z_hi = getattr(core, "core_height", 0) or 200.0
        lines.append("% --- Surfaces ---")
        lines.append(f"surf 1 cyl 0 0 {r_core:.2f} 0 {z_hi:.2f}")
        lines.append("")

        # Cell cards
        lines.append("% --- Cells ---")
        lines.append("cell 1 0 fuel  -1")
        lines.append("cell 2 0 outside 1")
        lines.append("")

        # Cross section library - user must set path to Serpent data
        lines.append("% --- Neutron data (set path to your Serpent xs data) ---")
        lines.append('% set acel "/path/to/xsdata"')
        lines.append("")
        lines.append("% End of input")

        output_file.write_text("\n".join(lines))

    @staticmethod
    def import_reactor(input_file: Union[str, Path]) -> Dict[str, Any]:
        """
        Import reactor from Serpent format (basic parsing).

        Parses materials, surfaces, and cells into a structured dict suitable for
        round-trip workflows. Does not reconstruct full PrismaticCore geometry.

        Args:
            input_file: Path to Serpent input file

        Returns:
            Dictionary with 'materials', 'surfaces', 'cells', 'source', 'format'
        """
        input_file = Path(input_file)
        if not input_file.exists():
            raise FileNotFoundError(f"Serpent input file not found: {input_file}")

        text = input_file.read_text()
        materials: List[Dict[str, Any]] = []
        surfaces: List[Dict[str, Any]] = []
        cells: List[Dict[str, Any]] = []

        for line in text.splitlines():
            line_stripped = line.strip()
            if not line_stripped or line_stripped.startswith("%"):
                continue
            parts = line_stripped.split()
            if not parts:
                continue
            first = parts[0].lower()
            if first == "mat":
                # mat name moder lib ... or mat name dens ...
                if len(parts) >= 3:
                    materials.append({"name": parts[1], "params": parts[2:]})
            elif first == "surf":
                if len(parts) >= 3:
                    surfaces.append({"id": parts[1], "type": parts[2], "params": parts[3:]})
            elif first == "cell":
                if len(parts) >= 3:
                    cells.append({"id": parts[1], "params": parts[2:]})

        return {
            "materials": materials,
            "surfaces": surfaces,
            "cells": cells,
            "core": {"format": "serpent_parsed"},
            "source": str(input_file),
            "format": "serpent",
        }


def _get_core_from_reactor(reactor: Any) -> Any:
    """Extract core geometry from reactor (mirrors smrforge.io.openmc_export logic)."""
    if hasattr(reactor, "core") and reactor.core is not None:
        return reactor.core
    if hasattr(reactor, "_get_core"):
        return reactor._get_core()
    if hasattr(reactor, "_core") and reactor._core is not None:
        return reactor._core
    raise ValueError(
        "Reactor has no core geometry. Call build_core() or provide a core directly."
    )
