"""
Simple Markdown/PDF report generator for SMRForge Community.

Takes analysis results and produces a design summary report.
For full regulatory reports and traceability, use SMRForge Pro.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional, Union

from ..utils.logging import get_logger

logger = get_logger("smrforge.reporting.simple_report")


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def generate_markdown_report(
    results: Dict[str, Any],
    title: str = "SMRForge Design Summary",
    output_path: Optional[Union[str, Path]] = None,
) -> str:
    """
    Generate a Markdown report from analysis results.

    Args:
        results: Dictionary with keys such as k_eff, power_thermal_mw,
            power_distribution, design_name, etc.
        title: Report title.
        output_path: If set, write report to file.

    Returns:
        Report text as string.

    Example:
        >>> results = smr.analyze_preset("valar-10")
        >>> from smrforge.reporting import generate_markdown_report
        >>> report = generate_markdown_report(results, title="Valar-10 Analysis")
        >>> generate_markdown_report(results, output_path="design_report.md")
    """
    lines = [
        f"# {title}",
        "",
        f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
        "## Key Results",
        "",
        "| Parameter | Value |",
        "|-----------|-------|",
    ]

    # Key parameters to include (in order)
    key_params = [
        ("k_eff", "k-effective"),
        ("power_thermal_mw", "Power (MWth)"),
        ("design_name", "Design"),
        ("power_mw", "Power (MW)"),
    ]

    for key, label in key_params:
        val = results.get(key)
        if val is not None:
            if isinstance(val, float):
                lines.append(f"| {label} | {val:.6f} |")
            else:
                lines.append(f"| {label} | {val} |")

    # Power distribution summary if present (avoid "or" with numpy arrays)
    power_dist = results.get("power_distribution")
    if power_dist is None:
        power_dist = results.get("power")
    if power_dist is not None:
        try:
            import numpy as np

            arr = np.asarray(power_dist).flatten()
            if len(arr) > 0:
                lines.append(f"| Max power density (W/cm³) | {float(arr.max()):.4e} |")
                lines.append(
                    f"| Mean power density (W/cm³) | {float(arr.mean()):.4e} |"
                )
        except Exception:
            pass

    # Additional numeric results
    for key, val in results.items():
        if key in (
            "k_eff",
            "power_thermal_mw",
            "design_name",
            "power_mw",
            "power_distribution",
            "power",
        ):
            continue
        if isinstance(val, (int, float)):
            lines.append(f"| {key} | {val} |")
        elif isinstance(val, str) and len(val) < 80:
            lines.append(f"| {key} | {val} |")

    lines.extend(
        ["", "## Notes", "", "This report was generated by SMRForge Community.", ""]
    )
    lines.append(
        "*For full regulatory reports and traceability matrices, see SMRForge Pro.*"
    )
    lines.append("")

    report = "\n".join(lines)
    if output_path:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(report, encoding="utf-8")
    return report


def generate_pdf_report(
    results: Dict[str, Any],
    title: str = "SMRForge Design Summary",
    output_path: Optional[Union[str, Path]] = None,
) -> Optional[Path]:
    """
    Generate a PDF report from analysis results (optional).

    Requires weasyprint. If not available, generates Markdown and prints instructions.

    Args:
        results: Analysis results dict.
        title: Report title.
        output_path: Output PDF path. If None, uses design_report.pdf in cwd.

    Returns:
        Path to PDF file if successful, else None.
    """
    md = generate_markdown_report(results, title=title)
    out = Path(output_path or "design_report.pdf")
    out = out.with_suffix(".pdf")

    try:
        from weasyprint import HTML

        html_content = (
            "<!DOCTYPE html><html><head><meta charset='utf-8'>"
            "<style>body{font-family:sans-serif;margin:1in;}</style></head>"
            f"<body><pre>{_escape_html(md)}</pre></body></html>"
        )
        HTML(string=html_content).write_pdf(str(out))
        return out
    except ImportError:
        # Fallback: write Markdown and suggest conversion
        md_path = out.with_suffix(".md")
        md_path.write_text(md, encoding="utf-8")
        logger.warning(
            "weasyprint not installed. Markdown saved to %s. Install weasyprint for PDF, or convert manually: open in browser and Print to PDF.",
            md_path,
        )
        return None
