#!/usr/bin/env python3
"""
Validation test runner script.

This script runs comprehensive validation tests with real ENDF files and
generates validation reports with timing and benchmarking results.

Usage:
    python scripts/run_validation.py [--endf-dir PATH] [--output REPORT.txt] [--verbose]
"""

import argparse
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import pytest
from pathlib import Path
import json
from datetime import datetime

def main():
    parser = argparse.ArgumentParser(
        description="Run validation tests with ENDF files and generate reports"
    )
    parser.add_argument(
        "--endf-dir",
        type=Path,
        help="Path to ENDF-B-VIII.1 directory",
        default=None
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output file for validation report (default: validation_report_YYYYMMDD_HHMMSS.txt)",
        default=None
    )
    parser.add_argument(
        "--json-output",
        type=Path,
        help="Output file for JSON results (optional)",
        default=None
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Verbose output"
    )
    parser.add_argument(
        "--tests",
        nargs="+",
        help="Specific test files or patterns to run (default: all validation tests)",
        default=None
    )
    
    args = parser.parse_args()
    
    # Set ENDF directory if provided
    if args.endf_dir:
        import os
        os.environ['LOCAL_ENDF_DIR'] = str(args.endf_dir.absolute())
        print(f"Using ENDF directory: {args.endf_dir}")
    
    # Determine output file
    if args.output is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.output = Path(f"validation_report_{timestamp}.txt")
    
    # Determine which tests to run
    if args.tests is None:
        test_files = [
            "tests/test_validation_comprehensive.py",
            "tests/test_endf_workflows_e2e.py",
        ]
    else:
        test_files = args.tests
    
    print("=" * 80)
    print("SMRForge Validation Test Runner")
    print("=" * 80)
    print(f"Output file: {args.output}")
    print(f"Test files: {', '.join(test_files)}")
    print()
    
    # Build pytest command
    pytest_args = [
        *test_files,
        "-v",
        "--tb=short",
    ]
    
    if args.verbose:
        pytest_args.append("-s")
    
    # Run tests
    print("Running validation tests...")
    exit_code = pytest.main(pytest_args)
    
    # Note: Actual validation report generation would be done by the tests
    # This script runs the tests; the ValidationBenchmarker generates reports
    
    print()
    print("=" * 80)
    print(f"Validation tests completed. Exit code: {exit_code}")
    print(f"Check test output above for results.")
    print(f"Report will be generated by tests if ValidationBenchmarker is used.")
    print("=" * 80)
    
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
