#!/usr/bin/env python3
"""
Coverage Tracking Script

Tracks test coverage over time, stores historical data, and generates trend reports.
Integrates with pytest-cov to track coverage metrics.

Usage:
    python scripts/track_coverage.py --generate     # Generate coverage and store results
    python scripts/track_coverage.py --report       # Generate trend report
    python scripts/track_coverage.py --compare      # Compare with previous run
    python scripts/track_coverage.py --summary      # Show current summary
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Coverage data storage location
COVERAGE_DATA_DIR = Path("coverage_data")
COVERAGE_DATA_FILE = COVERAGE_DATA_DIR / "coverage_history.json"
COVERAGE_TRENDS_FILE = COVERAGE_DATA_DIR / "coverage_trends.json"


def load_coverage_json(json_file: Path) -> Optional[Dict]:
    """Load coverage data from JSON file generated by pytest-cov."""
    if not json_file.exists():
        return None
    try:
        with open(json_file, 'r') as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error loading coverage JSON: {e}", file=sys.stderr)
        return None


def extract_coverage_metrics(coverage_data: Dict) -> Dict:
    """Extract coverage metrics from pytest-cov JSON output."""
    if not coverage_data or 'totals' not in coverage_data:
        return {}
    
    totals = coverage_data['totals']
    metrics = {
        'overall': {
            'percent_covered': totals.get('percent_covered', 0),
            'covered_lines': totals.get('covered_lines', 0),
            'num_statements': totals.get('num_statements', 0),
            'missing_lines': totals.get('missing_lines', 0),
            'excluded_lines': totals.get('excluded_lines', 0),
        }
    }
    
    # Extract per-file coverage
    file_coverage = {}
    if 'files' in coverage_data:
        for filepath, file_data in coverage_data['files'].items():
            if 'summary' in file_data:
                summary = file_data['summary']
                # Convert Windows paths to Unix-style for consistency
                normalized_path = filepath.replace('\\', '/')
                file_coverage[normalized_path] = {
                    'percent_covered': summary.get('percent_covered', 0),
                    'covered_lines': summary.get('covered_lines', 0),
                    'num_statements': summary.get('num_statements', 0),
                    'missing_lines': summary.get('missing_lines', 0),
                }
    
    metrics['files'] = file_coverage
    return metrics


def load_history() -> List[Dict]:
    """Load historical coverage data."""
    if not COVERAGE_DATA_FILE.exists():
        return []
    
    try:
        with open(COVERAGE_DATA_FILE, 'r') as f:
            data = json.load(f)
            return data.get('history', [])
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error loading history: {e}", file=sys.stderr)
        return []


def save_history(history: List[Dict]):
    """Save historical coverage data."""
    COVERAGE_DATA_DIR.mkdir(exist_ok=True)
    
    data = {
        'last_updated': datetime.now().isoformat(),
        'history': history
    }
    
    with open(COVERAGE_DATA_FILE, 'w') as f:
        json.dump(data, f, indent=2)


def generate_coverage() -> Optional[Dict]:
    """Generate coverage report using pytest."""
    print("Generating coverage report...")
    
    # Run pytest with coverage
    cmd = [
        sys.executable, '-m', 'pytest',
        'tests/',
        '-n', 'auto',  # Parallel execution
        '--cov=smrforge',
        '--cov-report=json:coverage_current.json',
        '--cov-report=term',
        '-q'
    ]
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        print(result.stdout)
        
        # Load the generated coverage JSON
        coverage_file = Path("coverage_current.json")
        coverage_data = load_coverage_json(coverage_file)
        
        if coverage_data:
            metrics = extract_coverage_metrics(coverage_data)
            metrics['timestamp'] = datetime.now().isoformat()
            metrics['commit_hash'] = get_commit_hash()
            return metrics
        else:
            print("Error: Failed to extract coverage metrics", file=sys.stderr)
            return None
            
    except subprocess.CalledProcessError as e:
        print(f"Error running pytest: {e}", file=sys.stderr)
        print(e.stderr, file=sys.stderr)
        return None


def get_commit_hash() -> str:
    """Get current git commit hash."""
    try:
        result = subprocess.run(
            ['git', 'rev-parse', '--short', 'HEAD'],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def add_to_history(metrics: Dict):
    """Add current coverage metrics to history."""
    history = load_history()
    history.append(metrics)
    
    # Keep only last 100 entries
    if len(history) > 100:
        history = history[-100:]
    
    save_history(history)


def generate_summary(metrics: Dict):
    """Generate a summary of current coverage."""
    if not metrics:
        print("No coverage data available. Run with --generate first.")
        return
    
    overall = metrics.get('overall', {})
    files = metrics.get('files', {})
    
    print("\n" + "=" * 70)
    print("COVERAGE SUMMARY")
    print("=" * 70)
    print(f"Timestamp: {metrics.get('timestamp', 'Unknown')}")
    print(f"Commit:    {metrics.get('commit_hash', 'Unknown')}")
    print()
    print("Overall Coverage:")
    print(f"  Coverage:    {overall.get('percent_covered', 0):.2f}%")
    print(f"  Covered:     {overall.get('covered_lines', 0):,} lines")
    print(f"  Total:       {overall.get('num_statements', 0):,} statements")
    print(f"  Missing:     {overall.get('missing_lines', 0):,} lines")
    print(f"  Excluded:    {overall.get('excluded_lines', 0):,} lines")
    print()
    
    # Show module-level coverage
    print("Module Coverage (Top 20):")
    print("-" * 70)
    
    # Group by module
    module_coverage = {}
    for filepath, file_data in files.items():
        # Extract module path (e.g., smrforge/core/reactor_core.py -> core/reactor_core)
        parts = filepath.split('/')
        if 'smrforge' in parts:
            idx = parts.index('smrforge')
            if idx + 1 < len(parts):
                module_path = '/'.join(parts[idx+1:])
                if module_path.endswith('.py'):
                    module_path = module_path[:-3]
                module_coverage[module_path] = file_data
    
    # Sort by coverage percentage
    sorted_modules = sorted(
        module_coverage.items(),
        key=lambda x: x[1].get('percent_covered', 0),
        reverse=True
    )
    
    for i, (module, data) in enumerate(sorted_modules[:20], 1):
        coverage = data.get('percent_covered', 0)
        covered = data.get('covered_lines', 0)
        total = data.get('num_statements', 0)
        print(f"{i:2d}. {module:50s} {coverage:6.2f}% ({covered:5d}/{total:5d})")
    
    print("=" * 70)


def compare_with_previous(current_metrics: Dict) -> Optional[Tuple[Dict, Dict]]:
    """Compare current coverage with previous run."""
    history = load_history()
    
    if len(history) < 2:
        print("Not enough history to compare. Need at least 2 runs.")
        return None
    
    previous = history[-1]
    previous_overall = previous.get('overall', {})
    current_overall = current_metrics.get('overall', {})
    
    prev_coverage = previous_overall.get('percent_covered', 0)
    curr_coverage = current_overall.get('percent_covered', 0)
    diff = curr_coverage - prev_coverage
    
    print("\n" + "=" * 70)
    print("COVERAGE COMPARISON")
    print("=" * 70)
    print(f"Previous: {prev_coverage:.2f}% (from {previous.get('timestamp', 'Unknown')})")
    print(f"Current:  {curr_coverage:.2f}% (from {current_metrics.get('timestamp', 'Unknown')})")
    print(f"Change:   {diff:+.2f}%")
    print()
    
    if abs(diff) < 0.01:
        print("No significant change in overall coverage.")
    elif diff > 0:
        print(f"✅ Coverage increased by {diff:.2f}%")
    else:
        print(f"⚠️  Coverage decreased by {abs(diff):.2f}%")
    
    print("=" * 70)
    
    return previous, current_metrics


def generate_trend_report():
    """Generate trend report from historical data."""
    history = load_history()
    
    if len(history) < 2:
        print("Not enough history to generate trends. Need at least 2 runs.")
        return
    
    print("\n" + "=" * 70)
    print("COVERAGE TRENDS")
    print("=" * 70)
    
    # Calculate trends
    first = history[0]
    last = history[-1]
    
    first_overall = first.get('overall', {})
    last_overall = last.get('overall', {})
    
    first_coverage = first_overall.get('percent_covered', 0)
    last_coverage = last_overall.get('percent_covered', 0)
    total_change = last_coverage - first_coverage
    
    print(f"First run:  {first_coverage:.2f}% (from {first.get('timestamp', 'Unknown')})")
    print(f"Last run:   {last_coverage:.2f}% (from {last.get('timestamp', 'Unknown')})")
    print(f"Total change: {total_change:+.2f}% over {len(history)} runs")
    print()
    
    # Show recent trend (last 10 runs)
    print("Recent Trend (Last 10 runs):")
    print("-" * 70)
    
    recent = history[-10:]
    for entry in recent:
        timestamp = entry.get('timestamp', 'Unknown')
        coverage = entry.get('overall', {}).get('percent_covered', 0)
        commit = entry.get('commit_hash', 'Unknown')
        print(f"  {timestamp[:19]:20s} {coverage:6.2f}% ({commit})")
    
    print("=" * 70)


def main():
    parser = argparse.ArgumentParser(
        description='Track test coverage over time',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/track_coverage.py --generate   # Generate and store coverage
  python scripts/track_coverage.py --report     # Show trend report
  python scripts/track_coverage.py --compare    # Compare with previous
  python scripts/track_coverage.py --summary    # Show current summary
        """
    )
    
    parser.add_argument(
        '--generate',
        action='store_true',
        help='Generate coverage report and store results'
    )
    parser.add_argument(
        '--report',
        action='store_true',
        help='Generate trend report from history'
    )
    parser.add_argument(
        '--compare',
        action='store_true',
        help='Compare current coverage with previous run'
    )
    parser.add_argument(
        '--summary',
        action='store_true',
        help='Show summary of current coverage'
    )
    
    args = parser.parse_args()
    
    # If no flags provided, show help
    if not any([args.generate, args.report, args.compare, args.summary]):
        parser.print_help()
        return
    
    if args.generate:
        metrics = generate_coverage()
        if metrics:
            add_to_history(metrics)
            generate_summary(metrics)
    
    if args.summary:
        # Try to load current coverage if available
        current_file = Path("coverage_current.json")
        if current_file.exists():
            coverage_data = load_coverage_json(current_file)
            if coverage_data:
                metrics = extract_coverage_metrics(coverage_data)
                metrics['timestamp'] = datetime.now().isoformat()
                metrics['commit_hash'] = get_commit_hash()
                generate_summary(metrics)
            else:
                print("Error: Could not load coverage data. Run with --generate first.")
        else:
            # Load from most recent history
            history = load_history()
            if history:
                generate_summary(history[-1])
            else:
                print("No coverage data available. Run with --generate first.")
    
    if args.compare:
        # Generate current if not available
        current_file = Path("coverage_current.json")
        if not current_file.exists():
            print("No current coverage data. Generating...")
            metrics = generate_coverage()
            if not metrics:
                return
        else:
            coverage_data = load_coverage_json(current_file)
            if not coverage_data:
                print("Error: Could not load coverage data.")
                return
            metrics = extract_coverage_metrics(coverage_data)
            metrics['timestamp'] = datetime.now().isoformat()
            metrics['commit_hash'] = get_commit_hash()
        
        compare_with_previous(metrics)
    
    if args.report:
        generate_trend_report()


if __name__ == '__main__':
    main()
