#!/usr/bin/env python3
"""
Coverage Tracking Script

Tracks test coverage over time, stores historical data, and generates trend reports.
Integrates with pytest-cov to track coverage metrics.

Usage:
    python scripts/track_coverage.py --generate     # Generate coverage and store results
    python scripts/track_coverage.py --report       # Generate trend report
    python scripts/track_coverage.py --compare      # Compare with previous run
    python scripts/track_coverage.py --summary      # Show current summary
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Coverage data storage location
# Keep generated artifacts out of the repo root.
REPO_ROOT = Path(__file__).resolve().parents[1]
COVERAGE_BASE_DIR = REPO_ROOT / "coverage"
COVERAGE_GENERATED_DIR = COVERAGE_BASE_DIR / "generated"
COVERAGE_TRACKING_DIR = COVERAGE_BASE_DIR / "tracking"
COVERAGE_DATA_FILE = COVERAGE_TRACKING_DIR / "coverage_history.json"
COVERAGE_TRENDS_FILE = COVERAGE_TRACKING_DIR / "coverage_trends.json"


def load_coverage_json(json_file: Path) -> Optional[Dict]:
    """Load coverage data from JSON file generated by pytest-cov."""
    if not json_file.exists():
        return None
    try:
        with open(json_file, 'r') as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error loading coverage JSON: {e}", file=sys.stderr)
        return None


def extract_coverage_metrics(coverage_data: Dict) -> Dict:
    """Extract coverage metrics from pytest-cov JSON output."""
    if not coverage_data or 'totals' not in coverage_data:
        return {}
    
    totals = coverage_data['totals']
    metrics = {
        'overall': {
            'percent_covered': totals.get('percent_covered', 0),
            'covered_lines': totals.get('covered_lines', 0),
            'num_statements': totals.get('num_statements', 0),
            'missing_lines': totals.get('missing_lines', 0),
            'excluded_lines': totals.get('excluded_lines', 0),
        }
    }
    
    # Extract per-file coverage
    file_coverage = {}
    if 'files' in coverage_data:
        for filepath, file_data in coverage_data['files'].items():
            if 'summary' in file_data:
                summary = file_data['summary']
                # Convert Windows paths to Unix-style for consistency
                normalized_path = filepath.replace('\\', '/')
                file_coverage[normalized_path] = {
                    'percent_covered': summary.get('percent_covered', 0),
                    'covered_lines': summary.get('covered_lines', 0),
                    'num_statements': summary.get('num_statements', 0),
                    'missing_lines': summary.get('missing_lines', 0),
                }
    
    metrics['files'] = file_coverage
    return metrics


def load_history() -> List[Dict]:
    """Load historical coverage data."""
    if not COVERAGE_DATA_FILE.exists():
        return []
    
    try:
        with open(COVERAGE_DATA_FILE, 'r') as f:
            data = json.load(f)
            return data.get('history', [])
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error loading history: {e}", file=sys.stderr)
        return []


def save_history(history: List[Dict]):
    """Save historical coverage data."""
    COVERAGE_TRACKING_DIR.mkdir(parents=True, exist_ok=True)
    
    data = {
        'last_updated': datetime.now().isoformat(),
        'history': history
    }
    
    with open(COVERAGE_DATA_FILE, 'w') as f:
        json.dump(data, f, indent=2)


def generate_coverage() -> Optional[Dict]:
    """Generate coverage report using pytest."""
    print("Generating coverage report...")
    print("Note: This may take 10-30+ minutes due to large test suite...")
    
    # Fix encoding issue for Windows (COVERAGE_RUN_DIAGNOSIS.md)
    env = os.environ.copy()
    env['PYTHONIOENCODING'] = 'utf-8'
    
    # Run pytest with coverage
    # Note: Removed -n auto since pytest-xdist may not be available
    # For faster execution, users can manually add -n auto if pytest-xdist is installed
    COVERAGE_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    coverage_json_path = COVERAGE_GENERATED_DIR / "coverage_current.json"

    cmd = [
        sys.executable, '-m', 'pytest',
        'tests/',
        '--cov=smrforge',
        f'--cov-report=json:{coverage_json_path.as_posix()}',
        '--cov-report=term',
        '-q',
        '--ignore=tests/performance/test_performance_benchmarks.py',  # Exclude slow/failing tests
        '--maxfail=10',  # Continue despite some failures
    ]
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True, env=env, cwd=REPO_ROOT)
        print(result.stdout)
        
        # Load the generated coverage JSON
        coverage_data = load_coverage_json(coverage_json_path)
        
        if coverage_data:
            metrics = extract_coverage_metrics(coverage_data)
            metrics['timestamp'] = datetime.now().isoformat()
            metrics['commit_hash'] = get_commit_hash()
            print("\nCoverage generation complete!")
            return metrics
        else:
            print("Error: Failed to extract coverage metrics", file=sys.stderr)
            return None
            
    except subprocess.CalledProcessError as e:
        print(f"Error running pytest: {e}", file=sys.stderr)
        print(e.stderr, file=sys.stderr)
        return None


def get_commit_hash() -> str:
    """Get current git commit hash."""
    try:
        result = subprocess.run(
            ['git', 'rev-parse', '--short', 'HEAD'],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def add_to_history(metrics: Dict):
    """Add current coverage metrics to history."""
    history = load_history()
    history.append(metrics)
    
    # Keep only last 100 entries
    if len(history) > 100:
        history = history[-100:]
    
    save_history(history)


def generate_summary(metrics: Dict):
    """Generate a summary of current coverage."""
    if not metrics:
        print("No coverage data available. Run with --generate first.")
        return
    
    overall = metrics.get('overall', {})
    files = metrics.get('files', {})
    
    print("\n" + "=" * 70)
    print("COVERAGE SUMMARY")
    print("=" * 70)
    print(f"Timestamp: {metrics.get('timestamp', 'Unknown')}")
    print(f"Commit:    {metrics.get('commit_hash', 'Unknown')}")
    print()
    print("Overall Coverage:")
    print(f"  Coverage:    {overall.get('percent_covered', 0):.2f}%")
    print(f"  Covered:     {overall.get('covered_lines', 0):,} lines")
    print(f"  Total:       {overall.get('num_statements', 0):,} statements")
    print(f"  Missing:     {overall.get('missing_lines', 0):,} lines")
    print(f"  Excluded:    {overall.get('excluded_lines', 0):,} lines")
    print()
    
    # Show module-level coverage
    print("Module Coverage (Top 20):")
    print("-" * 70)
    
    # Group by module
    module_coverage = {}
    for filepath, file_data in files.items():
        # Extract module path (e.g., smrforge/core/reactor_core.py -> core/reactor_core)
        parts = filepath.split('/')
        if 'smrforge' in parts:
            idx = parts.index('smrforge')
            if idx + 1 < len(parts):
                module_path = '/'.join(parts[idx+1:])
                if module_path.endswith('.py'):
                    module_path = module_path[:-3]
                module_coverage[module_path] = file_data
    
    # Sort by coverage percentage
    sorted_modules = sorted(
        module_coverage.items(),
        key=lambda x: x[1].get('percent_covered', 0),
        reverse=True
    )
    
    for i, (module, data) in enumerate(sorted_modules[:20], 1):
        coverage = data.get('percent_covered', 0)
        covered = data.get('covered_lines', 0)
        total = data.get('num_statements', 0)
        print(f"{i:2d}. {module:50s} {coverage:6.2f}% ({covered:5d}/{total:5d})")
    
    print("=" * 70)


def compare_with_previous(current_metrics: Dict) -> Optional[Tuple[Dict, Dict]]:
    """Compare current coverage with previous run."""
    history = load_history()
    
    if len(history) < 2:
        print("Not enough history to compare. Need at least 2 runs.")
        return None
    
    previous = history[-1]
    previous_overall = previous.get('overall', {})
    current_overall = current_metrics.get('overall', {})
    
    prev_coverage = previous_overall.get('percent_covered', 0)
    curr_coverage = current_overall.get('percent_covered', 0)
    diff = curr_coverage - prev_coverage
    
    print("\n" + "=" * 70)
    print("COVERAGE COMPARISON")
    print("=" * 70)
    print(f"Previous: {prev_coverage:.2f}% (from {previous.get('timestamp', 'Unknown')})")
    print(f"Current:  {curr_coverage:.2f}% (from {current_metrics.get('timestamp', 'Unknown')})")
    print(f"Change:   {diff:+.2f}%")
    print()
    
    if abs(diff) < 0.01:
        print("No significant change in overall coverage.")
    elif diff > 0:
        print(f"✅ Coverage increased by {diff:.2f}%")
    else:
        print(f"⚠️  Coverage decreased by {abs(diff):.2f}%")
    
    print("=" * 70)
    
    return previous, current_metrics


def generate_trend_report():
    """Generate trend report from historical data."""
    history = load_history()
    
    if len(history) < 2:
        print("Not enough history to generate trends. Need at least 2 runs.")
        return
    
    print("\n" + "=" * 70)
    print("COVERAGE TRENDS")
    print("=" * 70)
    
    # Calculate trends
    first = history[0]
    last = history[-1]
    
    first_overall = first.get('overall', {})
    last_overall = last.get('overall', {})
    
    first_coverage = first_overall.get('percent_covered', 0)
    last_coverage = last_overall.get('percent_covered', 0)
    total_change = last_coverage - first_coverage
    
    print(f"First run:  {first_coverage:.2f}% (from {first.get('timestamp', 'Unknown')})")
    print(f"Last run:   {last_coverage:.2f}% (from {last.get('timestamp', 'Unknown')})")
    print(f"Total change: {total_change:+.2f}% over {len(history)} runs")
    print()
    
    # Show recent trend (last 10 runs)
    print("Recent Trend (Last 10 runs):")
    print("-" * 70)
    
    recent = history[-10:]
    for entry in recent:
        timestamp = entry.get('timestamp', 'Unknown')
        coverage = entry.get('overall', {}).get('percent_covered', 0)
        commit = entry.get('commit_hash', 'Unknown')
        print(f"  {timestamp[:19]:20s} {coverage:6.2f}% ({commit})")
    
    print("=" * 70)


COVERAGE_TRACKING_MD = REPO_ROOT / "COVERAGE_TRACKING.md"


def update_coverage_doc(coverage_json_path: Optional[Path] = None) -> bool:
    """
    Update COVERAGE_TRACKING.md "Latest full run" and "Quick Status" from coverage JSON.

    Reads coverage/generated/coverage.json (or coverage_current.json fallback, or
    coverage_json_path if provided), extracts totals, and rewrites the
    "Latest full run (Jan 2026):" line in COVERAGE_TRACKING.md.
    """
    cand = coverage_json_path or COVERAGE_GENERATED_DIR / "coverage.json"
    if not cand.exists():
        cand = COVERAGE_GENERATED_DIR / "coverage_current.json"
    if not cand.exists():
        print(f"No coverage JSON found at {COVERAGE_GENERATED_DIR / 'coverage.json'} or coverage_current.json.", file=sys.stderr)
        return False

    data = load_coverage_json(cand)
    if not data:
        print("Could not load coverage JSON.", file=sys.stderr)
        return False

    tot = data.get("totals")
    if not tot and "files" in data:
        covered_lines = 0
        num_statements = 0
        missing_lines = 0
        excluded_lines = 0
        for finfo in data["files"].values():
            s = finfo.get("summary") if isinstance(finfo, dict) else None
            if s:
                covered_lines += s.get("covered_lines", 0)
                num_statements += s.get("num_statements", 0)
                missing_lines += s.get("missing_lines", 0)
                excluded_lines += s.get("excluded_lines", 0)
        pct = 100.0 * covered_lines / num_statements if num_statements else 0.0
        tot = {
            "percent_covered": pct,
            "covered_lines": covered_lines,
            "num_statements": num_statements,
            "missing_lines": missing_lines,
            "excluded_lines": excluded_lines,
        }
    if not tot:
        print("Coverage JSON missing 'totals' and could not derive from 'files'.", file=sys.stderr)
        return False

    pct = tot.get("percent_covered", 0)
    covered = tot.get("covered_lines", 0)
    total = tot.get("num_statements", 0)
    missing = tot.get("missing_lines", 0)
    gap80 = max(0.0, 80.0 - pct)
    gap90 = max(0.0, 90.0 - pct)

    year = datetime.now().strftime("%Y")
    new_line = (
        f"- **Latest full run (Jan {year}):** **{pct:.2f}%** "
        f"({covered:,} / {total:,} statements) — report: `coverage/generated/coverage.json`; "
        f"gap to 80%: {gap80:.2f}%; gap to 90%: {gap90:.2f}%."
    )

    if not COVERAGE_TRACKING_MD.exists():
        print(f"COVERAGE_TRACKING.md not found at {COVERAGE_TRACKING_MD}.", file=sys.stderr)
        return False

    text = COVERAGE_TRACKING_MD.read_text(encoding="utf-8")
    pattern = (
        r"- \*\*Latest full run \(Jan \d{4}\):\*\* \*\*[\d.]+%\*\* "
        r"\([\d,]+ / [\d,]+ statements\)[^.\n]*— report: [^;]+; "
        r"gap to 80%: [\d.]+%[^;]*; gap to 90%: [\d.]+%\."
    )
    if not re.search(pattern, text):
        print("Could not find 'Latest full run' line in COVERAGE_TRACKING.md.", file=sys.stderr)
        return False

    new_text = re.sub(pattern, new_line, text)
    COVERAGE_TRACKING_MD.write_text(new_text, encoding="utf-8")
    print(f"Updated COVERAGE_TRACKING.md: {pct:.2f}% ({covered:,} / {total:,} statements), gap to 90%: {gap90:.2f}%")
    return True


def main():
    parser = argparse.ArgumentParser(
        description='Track test coverage over time',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/track_coverage.py --generate   # Generate and store coverage
  python scripts/track_coverage.py --report     # Show trend report
  python scripts/track_coverage.py --compare    # Compare with previous
  python scripts/track_coverage.py --summary    # Show current summary
  python scripts/track_coverage.py --update-doc # Update COVERAGE_TRACKING.md from coverage JSON
        """
    )
    
    parser.add_argument(
        '--generate',
        action='store_true',
        help='Generate coverage report and store results'
    )
    parser.add_argument(
        '--report',
        action='store_true',
        help='Generate trend report from history'
    )
    parser.add_argument(
        '--compare',
        action='store_true',
        help='Compare current coverage with previous run'
    )
    parser.add_argument(
        '--summary',
        action='store_true',
        help='Show summary of current coverage'
    )
    parser.add_argument(
        '--update-doc',
        action='store_true',
        help='Update COVERAGE_TRACKING.md from coverage/generated/coverage.json (or coverage_current.json)'
    )
    parser.add_argument(
        '--coverage-json',
        type=Path,
        default=None,
        help='Path to coverage JSON (used with --update-doc)'
    )
    
    args = parser.parse_args()
    
    # If no flags provided, show help
    if not any([args.generate, args.report, args.compare, args.summary, args.update_doc]):
        parser.print_help()
        return
    
    if args.generate:
        metrics = generate_coverage()
        if metrics:
            add_to_history(metrics)
            generate_summary(metrics)
    
    if args.summary:
        # Try to load current coverage if available
        current_file = COVERAGE_GENERATED_DIR / "coverage_current.json"
        if current_file.exists():
            coverage_data = load_coverage_json(current_file)
            if coverage_data:
                metrics = extract_coverage_metrics(coverage_data)
                metrics['timestamp'] = datetime.now().isoformat()
                metrics['commit_hash'] = get_commit_hash()
                generate_summary(metrics)
            else:
                print("Error: Could not load coverage data. Run with --generate first.")
        else:
            # Load from most recent history
            history = load_history()
            if history:
                generate_summary(history[-1])
            else:
                print("No coverage data available. Run with --generate first.")
    
    if args.compare:
        # Generate current if not available
        current_file = COVERAGE_GENERATED_DIR / "coverage_current.json"
        if not current_file.exists():
            print("No current coverage data. Generating...")
            metrics = generate_coverage()
            if not metrics:
                return
        else:
            coverage_data = load_coverage_json(current_file)
            if not coverage_data:
                print("Error: Could not load coverage data.")
                return
            metrics = extract_coverage_metrics(coverage_data)
            metrics['timestamp'] = datetime.now().isoformat()
            metrics['commit_hash'] = get_commit_hash()
        
        compare_with_previous(metrics)
    
    if args.report:
        generate_trend_report()

    if args.update_doc:
        ok = update_coverage_doc(args.coverage_json)
        if not ok:
            sys.exit(1)


if __name__ == '__main__':
    main()
