"""
Automated regulatory submission package generator (Pro).

One command → produce a complete NRC/IAEA-ready submission package:
- Inputs and outputs in required formats
- Traceability matrices
- Uncertainty and margin documentation
"""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from smrforge.utils.logging import get_logger

logger = get_logger("smrforge_pro.workflows.regulatory_package")


@dataclass
class RegulatoryPackageConfig:
    """Configuration for regulatory package generation."""

    framework: str = "NRC"  # NRC, IAEA, ANS
    include_uncertainty: bool = True
    include_traceability: bool = True
    include_margins: bool = True


def generate_regulatory_package(
    reactor: Any,
    results: Optional[Dict[str, Any]] = None,
    output_dir: Optional[Path] = None,
    config: Optional[RegulatoryPackageConfig] = None,
) -> Path:
    """
    Generate a regulatory submission package.

    Args:
        reactor: Reactor instance or preset name
        results: Optional solve results (if None, will run solve)
        output_dir: Output directory (default: regulatory_package/)
        config: Package configuration

    Returns:
        Path to generated package directory
    """
    if output_dir is None:
        output_dir = Path("regulatory_package")
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if config is None:
        config = RegulatoryPackageConfig()

    try:
        from smrforge.convenience import create_reactor, get_design_point
    except ImportError:
        raise ImportError(
            "generate_regulatory_package requires smrforge. pip install smrforge"
        ) from None

    if isinstance(reactor, str):
        reactor = create_reactor(reactor)

    if results is None:
        results = reactor.solve()

    design_point = get_design_point(reactor) if hasattr(reactor, "spec") else {}

    # 1. Input summary
    inputs = {}
    if hasattr(reactor, "spec"):
        spec = reactor.spec
        if hasattr(spec, "model_dump"):
            inputs = spec.model_dump()
        else:
            inputs = {
                "name": getattr(spec, "name", "reactor"),
                "power_thermal": getattr(spec, "power_thermal", 0),
                "enrichment": getattr(spec, "enrichment", 0),
                "core_height": getattr(spec, "core_height", 0),
                "core_diameter": getattr(spec, "core_diameter", 0),
            }

    (output_dir / "inputs.json").write_text(
        json.dumps(inputs, indent=2, default=str), encoding="utf-8"
    )

    # 2. Output summary
    outputs = {
        "k_eff": results.get("k_eff"),
        "power_thermal_mw": design_point.get("power_thermal_mw"),
        **{k: v for k, v in results.items() if k not in ("k_eff",)},
    }
    (output_dir / "outputs.json").write_text(
        json.dumps(outputs, indent=2, default=str), encoding="utf-8"
    )

    # 3. Traceability matrix template
    if config.include_traceability:
        traceability = {
            "framework": config.framework,
            "sections": [
                {"id": "1", "title": "Reactor Input", "reference": "inputs.json"},
                {"id": "2", "title": "Physics Results", "reference": "outputs.json"},
                {"id": "3", "title": "Safety Margins", "reference": "safety_margins.json"},
            ],
        }
        (output_dir / "traceability_matrix.json").write_text(
            json.dumps(traceability, indent=2), encoding="utf-8"
        )

    # 4. Safety margins (if available)
    if config.include_margins:
        try:
            from smrforge.validation.safety_report import safety_margin_report

            report = safety_margin_report(reactor)
            margins_data = report.to_dict()
        except Exception as e:
            margins_data = {"error": str(e), "margins": []}
        (output_dir / "safety_margins.json").write_text(
            json.dumps(margins_data, indent=2), encoding="utf-8"
        )

    # 5. Uncertainty placeholder
    if config.include_uncertainty:
        uncertainty_placeholder = {
            "note": "Run UQ workflow and add uncertainty_summary.json",
            "k_eff_std": None,
            "sources": [],
        }
        (output_dir / "uncertainty_placeholder.json").write_text(
            json.dumps(uncertainty_placeholder, indent=2), encoding="utf-8"
        )

    # 6. README
    readme = f"""# Regulatory Submission Package
Framework: {config.framework}
Generated by SMRForge Pro

## Contents
- inputs.json: Reactor input specification
- outputs.json: Physics calculation results
- traceability_matrix.json: Traceability matrix template
- safety_margins.json: Safety margin report
- uncertainty_placeholder.json: Placeholder for UQ results

## Next Steps
1. Run UQ: smrforge workflow uq --reactor reactor.json --params enrichment:0.195:normal:0.02
2. Add uncertainty_summary.json to this package
3. Complete traceability matrix with document references
4. Submit per {config.framework} requirements
"""
    (output_dir / "README.md").write_text(readme, encoding="utf-8")

    logger.info(f"Regulatory package written to {output_dir}")
    return output_dir
